# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ship.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ship.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nship.proto\x12\x04ship\"\xf6\x02\n\x04Ship\x12\'\n\talignment\x18\x01 \x01(\x0e\x32\x14.ship.Ship.Alignment\x12\x0c\n\x04name\x18\x02 \x01(\t\x12$\n\nclass_ship\x18\x03 \x01(\x0e\x32\x10.ship.Ship.Class\x12\x0e\n\x06length\x18\x04 \x01(\x02\x12\x0c\n\x04size\x18\x05 \x01(\x05\x12\r\n\x05\x61rmed\x18\x06 \x01(\x08\x12$\n\x08officers\x18\x07 \x03(\x0b\x32\x12.ship.Ship.Officer\x1a>\n\x07Officer\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x0c\n\x04rank\x18\x03 \x01(\t\" \n\tAlignment\x12\x08\n\x04\x41LLY\x10\x00\x12\t\n\x05\x45NEMY\x10\x01\"\\\n\x05\x43lass\x12\x0c\n\x08\x43orvette\x10\x00\x12\x0b\n\x07\x46rigate\x10\x01\x12\x0b\n\x07\x43ruiser\x10\x02\x12\r\n\tDestroyer\x10\x03\x12\x0b\n\x07\x43\x61rrier\x10\x04\x12\x0f\n\x0b\x44readnought\x10\x05\">\n\x0b\x43oordinates\x12\r\n\x05hours\x18\x01 \x01(\x05\x12\x0f\n\x07minutes\x18\x02 \x01(\x05\x12\x0f\n\x07seconds\x18\x03 \x01(\x01\x32@\n\x0eServerResponce\x12.\n\tRouteChat\x12\x11.ship.Coordinates\x1a\n.ship.Ship(\x01\x30\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ship_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SHIP']._serialized_start=21
  _globals['_SHIP']._serialized_end=395
  _globals['_SHIP_OFFICER']._serialized_start=205
  _globals['_SHIP_OFFICER']._serialized_end=267
  _globals['_SHIP_ALIGNMENT']._serialized_start=269
  _globals['_SHIP_ALIGNMENT']._serialized_end=301
  _globals['_SHIP_CLASS']._serialized_start=303
  _globals['_SHIP_CLASS']._serialized_end=395
  _globals['_COORDINATES']._serialized_start=397
  _globals['_COORDINATES']._serialized_end=459
  _globals['_SERVERRESPONCE']._serialized_start=461
  _globals['_SERVERRESPONCE']._serialized_end=525
# @@protoc_insertion_point(module_scope)
