# Generated by Django 5.1.4 on 2025-01-10 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio_uploader', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Audio',
            new_name='AudioFile',
        ),
        migrations.DeleteModel(
            name='AudioName',
        ),
        migrations.RenameField(
            model_name='audiofile',
            old_name='audio_file',
            new_name='file',
        ),
    ]
